### ISSUE TITLE
Doesn't work with ui-router 1.x

### ISSUE THREAD

**Issue by chasedeanda** [HourlyNerd/remove-angular-modules-loader#2]
Recently upgraded to ui-router 1.x from 0.4.2 and my build started failing.
```
ERROR in ./~/angular-ui-router/lib/angular.js
Module parse failed: /Users/cdeanda/dev/av-web/public/client/node_modules/remove-angular-modules-loader/index.js?moduleName=av-web!/Users/cdeanda/dev/av-web/public/client/node_modules/angular-ui-router/lib/angular.js Unexpected token (30:1)
You may need an appropriate loader to handle this file type.
|      var node = document.querySelectorAll('[ng-app]');
|      node && node[0] && node[0].setAttribute('ng-app', moduleName);
|  })(window.angular, "av-web", ["protractorBaseModule_"], [], false);
|  ;
```
Tried whitelisting ui-router, but that didn't seem to work. Really have no idea what's going on and why upgrading that package would cause this to stop working. Any help would be greatly appreciated, thanks.

**Comment by mkoryak** [comment]
aha! I see the problem. 

you probably load the loader like the example says:

```
{
    test: /\/angular(.min)?\.js$/,
    loader: 'remove-angular-modules'
},
```

and angular-iu-router now contains `angular.js` in there. you need to make your test more specific to target just the angular's angular.js file. I think this might work:

`test: /angular\/angular(.min)?\.js$/,`

otherwise figure out a better regexp. If memory serves me right, there is also an `exclude` option you can use there in loader config

**Comment by chasedeanda** [comment]
Ah, I did notice that ui-router was referencing it's own copy of angular.js. Thanks for the help and the quick response 👍 , this makes total sense!

**Comment by mkoryak** [comment]
I am curious, what was the solution?

**Comment by chasedeanda** [comment]
You're proposed solution worked: `test: /angular\/angular(.min)?\.js$/,`
